name: quiz_app_f4
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # getx state managment bilan ishlash uchun
  get: ^4.7.3
  # svg rasmlar olish va ishlatish uchun
  flutter_svg: ^2.2.3
  # http service va backend bilan ishlash uchun
  http: ^1.6.0
  # ilovani moslashuvchan qilish uchun
  flutter_screenutil: ^5.9.3
  # ilovadan rasmlar olish uchun
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icons/
